logging:
  level:
    root: info
    org.springframework: info
  pattern:
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
