server:
  port: 8085

logging:
  level:
    root: info
    org.springframework: info
  pattern:
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5

  file:
    name: remove-movie.log